let Catalog = [
    {id: 1, price: "250Gel",type:'კედლის', title: 'კედლის თეფშები და საათებ', img: './imgs/production/კედლისთეფშებიდასაათები/1.jpg'},
    {id: 2, price: "250Gel",type:'კედლის', title: 'კედლის თეფშები და საათებ', img: './imgs/production/კედლისთეფშებიდასაათები/2.jpg'},
    {id: 3, price: "250Gel",type:'კედლის', title: 'კედლის თეფშები და საათებ', img: './imgs/production/კედლისთეფშებიდასაათები/3.jpg'},
    {id: 4, price: "250Gel",type:'კედლის', title: 'კედლის თეფშები და საათებ', img: './imgs/production/კედლისთეფშებიდასაათები/4.jpg'},
    {id: 5, price: "250Gel",type:'კედლის', title: 'კედლის თეფშები და საათებ', img: './imgs/production/კედლისთეფშებიდასაათები/5.jpg'},
    {id: 6, price: "250Gel",type:'კედლის', title: 'კედლის თეფშები და საათებ', img: './imgs/production/კედლისთეფშებიდასაათები/6.jpg'},
    {id: 7, price: "250Gel",type:'კედლის', title: 'კედლის თეფშები და საათებ', img: './imgs/production/კედლისთეფშებიდასაათები/7.jpg'},
    {id: 8, price: "250Gel",type:'კედლის', title: 'კედლის თეფშები და საათებ', img: './imgs/production/კედლისთეფშებიდასაათები/8.jpg'},
    {id: 9, price: "250Gel",type:'კედლის', title: 'კედლის თეფშები და საათებ', img: './imgs/production/კედლისთეფშებიდასაათები/9.jpg'},
    {id: 10, price: "250Gel",type:'კედლის', title: 'კედლის თეფშები და საათებ', img: './imgs/production/კედლისთეფშებიდასაათები/10.jpg'},
    {id: 11, price: "250Gel",type:'კედლის', title: 'კედლის თეფშები და საათებ', img: './imgs/production/კედლისთეფშებიდასაათები/11.jpg'},
    {id: 12, price: "250Gel",type:'კედლის', title: 'კედლის თეფშები და საათებ', img: './imgs/production/კედლისთეფშებიდასაათები/12.jpg'},
    {id: 13, price: '150gel', title: 'ლარნაკები', img: './imgs/production/ლარნაკები/1.jpg'},
    {id: 14, price: '150gel', title: 'ლარნაკები', img: './imgs/production/ლარნაკები/2.jpg'},
    {id: 15, price: '150gel', title: 'ლარნაკები', img: './imgs/production/ლარნაკები/3.jpg'},
    {id: 16, price: '150gel', title: 'ლარნაკები', img: './imgs/production/ლარნაკები/4.jpg'},
    {id: 17, price: '150gel', title: 'ლარნაკები', img: './imgs/production/ლარნაკები/5.jpg'},
    {id: 18, price: '150gel', title: 'ლარნაკები', img: './imgs/production/ლარნაკები/6.jpg'},
    {id: 19, price: '150gel', title: 'ლარნაკები', img: './imgs/production/ლარნაკები/7.jpg'},

    {id: 20, price: '50Gel', title: 'ნიჟარა', img: './imgs/production/ნიჟარები/1.JPG'},
    {id: 21, price: '50Gel', title: 'ნიჟარა', img: './imgs/production/ნიჟარები/2.JPG'},
    {id: 22, price: '50Gel', title: 'ნიჟარა', img: './imgs/production/ნიჟარები/3.JPG'},
    {id: 23, price: '50Gel', title: 'ნიჟარა', img: './imgs/production/ნიჟარები/4.JPG'},
    {id: 24, price: '50Gel', title: 'ნიჟარა', img: './imgs/production/ნიჟარები/5.JPG'},
    {id: 25, price: '50Gel', title: 'ნიჟარა', img: './imgs/production/ნიჟარები/6.JPG'},
    {id: 26, price: '50Gel', title: 'ნიჟარა', img: './imgs/production/ნიჟარები/7.JPG'},
    {id: 27, price: '50Gel', title: 'ნიჟარა', img: './imgs/production/ნიჟარები/8.JPG'},
    {id: 28, price: '50Gel', title: 'ნიჟარა', img: './imgs/production/ნიჟარები/9.JPG'},
    {id: 29, price: '50Gel', title: 'ნიჟარა', img: './imgs/production/ნიჟარები/10.JPG'},
    {id: 30, price: '50Gel', title: 'ნიჟარა', img: './imgs/production/ნიჟარები/11.JPG'},

    {id: 31, price: '87Gel', title: 'სამზარეულო', img: './imgs/production/სამზარეულო/1.JPG'},
    {id: 32, price: '87Gel', title: 'სამზარეულო', img: './imgs/production/სამზარეულო/2.JPG'},
    {id: 33, price: '87Gel', title: 'სამზარეულო', img: './imgs/production/სამზარეულო/3.JPG'},
    {id: 34, price: '87Gel', title: 'სამზარეულო', img: './imgs/production/სამზარეულო/4.JPG'},
    {id: 35, price: '87Gel', title: 'სამზარეულო', img: './imgs/production/სამზარეულო/5.JPG'},
    {id: 36, price: '87Gel', title: 'სამზარეულო', img: './imgs/production/სამზარეულო/6.JPG'},

    {id: 37, price: '87Gel', title: 'სამზარეულო', img: './imgs/production/სამზარეულო/7.JPG'},
    {id: 38, price: '87Gel', title: 'სამზარეულო', img: './imgs/production/სამზარეულო/8.JPG'},
    {id: 39, price: '87Gel', title: 'სამზარეულო', img: './imgs/production/სამზარეულო/9.JPG'},
    {id: 40, price: '87Gel', title: 'სამზარეულო', img: './imgs/production/სამზარეულო/10.JPG'},
    {id: 41, price: '87Gel', title: 'სამზარეულო', img: './imgs/production/სამზარეულო/11.JPG'},
    {id: 42, price: '87Gel', title: 'სამზარეულო', img: './imgs/production/სამზარეულო/12.JPG'},
    {id: 43, price: '87Gel', title: 'სამზარეულო', img: './imgs/production/სამზარეულო/13.JPG'},
    {id: 44, price: '87Gel', title: 'სამზარეულო', img: './imgs/production/სამზარეულო/14.JPG'},
    {id: 45, price: '87Gel', title: 'სამზარეულო', img: './imgs/production/სამზარეულო/15.JPG'},
    {id: 46, price: '87Gel', title: 'სამზარეულო', img: './imgs/production/სამზარეულო/16.JPG'},
    {id: 47, price: '87Gel', title: 'სამზარეულო', img: './imgs/production/სამზარეულო/17.JPG'},
    {id: 47, price: '93Gel', title: 'სანათი', img: './imgs/production/სანათები/1.JPG'},
    {id: 48, price: '93Gel', title: 'სანათი', img: './imgs/production/სანათები/2.JPG'},
    {id: 49, price: '93Gel', title: 'სანათი', img: './imgs/production/სანათები/3.JPG'},
    {id: 50, price: '93Gel', title: 'სანათი', img: './imgs/production/სანათები/4.JPG'},
    {id: 51, price: '93Gel', title: 'სანათი', img: './imgs/production/სანათები/5.JPG'},
    {id: 52, price: '93Gel', title: 'სანათი', img: './imgs/production/სანათები/6.JPG'},
    {id: 53, price: '93Gel', title: 'სანათი', img: './imgs/production/სანათები/7.JPG'},
    {id: 54, price: '93Gel', title: 'სანათი', img: './imgs/production/სანათები/8.JPG'},
    {id: 55, price: '93Gel', title: 'სანათი', img: './imgs/production/სანათები/9.JPG'},
    {id: 56, price: '93Gel', title: 'სანათი', img: './imgs/production/სანათები/10.JPG'},
    {id: 57, price: '93Gel', title: 'სანათი', img: './imgs/production/სანათები/11.JPG'},
    {id: 58, price: '93Gel', title: 'სანათი', img: './imgs/production/სანათები/12.JPG'},
    {id: 59, price: '93Gel', title: 'სანათი', img: './imgs/production/სანათები/13.JPG'},
    {id: 60, price: '93Gel', title: 'სანათი', img: './imgs/production/სანათები/14.JPG'},
    {id: 61, price: '93Gel', title: 'სანათი', img: './imgs/production/სანათები/15.JPG'},
    {id: 62, price: '93Gel', title: 'სანათი', img: './imgs/production/სანათები/16.JPG'},
    {id: 63, price: '93Gel', title: 'სანათი', img: './imgs/production/სანათები/17.JPG'},
    {id: 64, price: '93Gel', title: 'სანათი', img: './imgs/production/სანათები/18.JPG'},
    {id: 65, price: '93Gel', title: 'სანათი', img: './imgs/production/სანათები/19.JPG'},
    {id: 66, price: '93Gel', title: 'სანათი', img: './imgs/production/სანათები/20.JPG'},
    {id: 67, price: '93Gel', title: 'სანათი', img: './imgs/production/სანათები/21.JPG'},
    {id: 68, price: '93Gel', title: 'სანათი', img: './imgs/production/სანათები/22.JPG'},
    {id: 69, price: '93Gel', title: 'სანათი', img: './imgs/production/სანათები/23.JPG'},
    {id: 70, price: '93Gel', title: 'სანათი', img: './imgs/production/სანათები/24.JPG'},
    {id: 71, price: '93Gel', title: 'სანათი', img: './imgs/production/სანათები/25.JPG'},
    {id: 72, price: '93Gel', title: 'სანათი', img: './imgs/production/სანათები/26.JPG'},
    {id: 73, price: '93Gel', title: 'სანათი', img: './imgs/production/სანათები/27.JPG'},

    {id: 74, price: '44Gel', title: 'სახლის დეკორი', img: './imgs/production/სახლისდეკორი/1.JPG'},
    {id: 75, price: '44Gel', title: 'სახლის დეკორი', img: './imgs/production/სახლისდეკორი/2.JPG'},

    {id: 76, price: '44Gel', title: 'სახლის დეკორი', img: './imgs/production/სახლისდეკორი/3.JPG'},
    {id: 77, price: '44Gel', title: 'სახლის დეკორი', img: './imgs/production/სახლისდეკორი/4.JPG'},
    {id: 78, price: '44Gel', title: 'სახლის დეკორი', img: './imgs/production/სახლისდეკორი/5.JPG'},
    {id: 79, price: '44Gel', title: 'სახლის დეკორი', img: './imgs/production/სახლისდეკორი/6.JPG'},
    {id: 80, price: '44Gel', title: 'სახლის დეკორი', img: './imgs/production/სახლისდეკორი/7.JPG'},
    {id: 81, price: '44Gel', title: 'სახლის დეკორი', img: './imgs/production/სახლისდეკორი/8.JPG'},
]

